# Generated by Django 3.1.7 on 2021-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=10)),
                ('last_Name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=230)),
            ],
        ),
    ]
