# Generated by Django 3.1.7 on 2021-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=1, max_length=33),
            preserve_default=False,
        ),
    ]
